package com.pojos.model;
// Generated May 28, 2015 4:10:50 PM by Hibernate Tools 3.6.0



/**
 * BancoentidadesId generated by hbm2java
 */
public class BancoentidadesId  implements java.io.Serializable {


     private int idBanco;
     private String idEntidad;
     private int numeroCuenta;

    public BancoentidadesId() {
    }

    public BancoentidadesId(int idBanco, String idEntidad, int numeroCuenta) {
       this.idBanco = idBanco;
       this.idEntidad = idEntidad;
       this.numeroCuenta = numeroCuenta;
    }
   
    public int getIdBanco() {
        return this.idBanco;
    }
    
    public void setIdBanco(int idBanco) {
        this.idBanco = idBanco;
    }
    public String getIdEntidad() {
        return this.idEntidad;
    }
    
    public void setIdEntidad(String idEntidad) {
        this.idEntidad = idEntidad;
    }
    public int getNumeroCuenta() {
        return this.numeroCuenta;
    }
    
    public void setNumeroCuenta(int numeroCuenta) {
        this.numeroCuenta = numeroCuenta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BancoentidadesId) ) return false;
		 BancoentidadesId castOther = ( BancoentidadesId ) other; 
         
		 return (this.getIdBanco()==castOther.getIdBanco())
 && ( (this.getIdEntidad()==castOther.getIdEntidad()) || ( this.getIdEntidad()!=null && castOther.getIdEntidad()!=null && this.getIdEntidad().equals(castOther.getIdEntidad()) ) )
 && (this.getNumeroCuenta()==castOther.getNumeroCuenta());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdBanco();
         result = 37 * result + ( getIdEntidad() == null ? 0 : this.getIdEntidad().hashCode() );
         result = 37 * result + this.getNumeroCuenta();
         return result;
   }   


}


