package com.pojos.model;
// Generated May 28, 2015 4:10:50 PM by Hibernate Tools 3.6.0



/**
 * Bancoentidades generated by hbm2java
 */
public class Bancoentidades  implements java.io.Serializable {


     private BancoentidadesId id;
     private Entidades entidades;
     private Bancos bancos;

    public Bancoentidades() {
    }

	
    public Bancoentidades(BancoentidadesId id, Entidades entidades) {
        this.id = id;
        this.entidades = entidades;
    }
    public Bancoentidades(BancoentidadesId id, Entidades entidades, Bancos bancos) {
       this.id = id;
       this.entidades = entidades;
       this.bancos = bancos;
    }
   
    public BancoentidadesId getId() {
        return this.id;
    }
    
    public void setId(BancoentidadesId id) {
        this.id = id;
    }
    public Entidades getEntidades() {
        return this.entidades;
    }
    
    public void setEntidades(Entidades entidades) {
        this.entidades = entidades;
    }
    public Bancos getBancos() {
        return this.bancos;
    }
    
    public void setBancos(Bancos bancos) {
        this.bancos = bancos;
    }




}


