package com.pojos.model;
// Generated May 28, 2015 4:10:50 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Ciudades generated by hbm2java
 */
public class Ciudades  implements java.io.Serializable {


     private int idCiudad;
     private String ciudad;
     private Set detallesubregions = new HashSet(0);

    public Ciudades() {
    }

	
    public Ciudades(int idCiudad) {
        this.idCiudad = idCiudad;
    }
    public Ciudades(int idCiudad, String ciudad, Set detallesubregions) {
       this.idCiudad = idCiudad;
       this.ciudad = ciudad;
       this.detallesubregions = detallesubregions;
    }
   
    public int getIdCiudad() {
        return this.idCiudad;
    }
    
    public void setIdCiudad(int idCiudad) {
        this.idCiudad = idCiudad;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public Set getDetallesubregions() {
        return this.detallesubregions;
    }
    
    public void setDetallesubregions(Set detallesubregions) {
        this.detallesubregions = detallesubregions;
    }




}


