package com.pojos.model;
// Generated May 28, 2015 4:10:50 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Conduccionsistemas generated by hbm2java
 */
public class Conduccionsistemas  implements java.io.Serializable {


     private Integer idConduccionSistema;
     private String conduccionSistema;
     private Set detallevariedadeses = new HashSet(0);

    public Conduccionsistemas() {
    }

    public Conduccionsistemas(String conduccionSistema, Set detallevariedadeses) {
       this.conduccionSistema = conduccionSistema;
       this.detallevariedadeses = detallevariedadeses;
    }
   
    public Integer getIdConduccionSistema() {
        return this.idConduccionSistema;
    }
    
    public void setIdConduccionSistema(Integer idConduccionSistema) {
        this.idConduccionSistema = idConduccionSistema;
    }
    public String getConduccionSistema() {
        return this.conduccionSistema;
    }
    
    public void setConduccionSistema(String conduccionSistema) {
        this.conduccionSistema = conduccionSistema;
    }
    public Set getDetallevariedadeses() {
        return this.detallevariedadeses;
    }
    
    public void setDetallevariedadeses(Set detallevariedadeses) {
        this.detallevariedadeses = detallevariedadeses;
    }




}


