package com.pojos.model;
// Generated May 28, 2015 4:10:50 PM by Hibernate Tools 3.6.0



/**
 * DetallevariedadcuartelesId generated by hbm2java
 */
public class DetallevariedadcuartelesId  implements java.io.Serializable {


     private int idDetalleVariedad;
     private int idDireccion;

    public DetallevariedadcuartelesId() {
    }

    public DetallevariedadcuartelesId(int idDetalleVariedad, int idDireccion) {
       this.idDetalleVariedad = idDetalleVariedad;
       this.idDireccion = idDireccion;
    }
   
    public int getIdDetalleVariedad() {
        return this.idDetalleVariedad;
    }
    
    public void setIdDetalleVariedad(int idDetalleVariedad) {
        this.idDetalleVariedad = idDetalleVariedad;
    }
    public int getIdDireccion() {
        return this.idDireccion;
    }
    
    public void setIdDireccion(int idDireccion) {
        this.idDireccion = idDireccion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetallevariedadcuartelesId) ) return false;
		 DetallevariedadcuartelesId castOther = ( DetallevariedadcuartelesId ) other; 
         
		 return (this.getIdDetalleVariedad()==castOther.getIdDetalleVariedad())
 && (this.getIdDireccion()==castOther.getIdDireccion());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdDetalleVariedad();
         result = 37 * result + this.getIdDireccion();
         return result;
   }   


}


