package com.pojos.model;
// Generated May 28, 2015 4:10:50 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Detallevariedades generated by hbm2java
 */
public class Detallevariedades  implements java.io.Serializable {


     private Integer idDetalleVariedad;
     private Conduccionsistemas conduccionsistemas;
     private Riegosistemas riegosistemas;
     private Variedades variedades;
     private Integer cantidadPlantas;
     private Float tamanioHectariaVariedad;
     private Integer anio;
     private Set detallevariedadcuarteleses = new HashSet(0);

    public Detallevariedades() {
    }

    public Detallevariedades(Conduccionsistemas conduccionsistemas, Riegosistemas riegosistemas, Variedades variedades, Integer cantidadPlantas, Float tamanioHectariaVariedad, Integer anio, Set detallevariedadcuarteleses) {
       this.conduccionsistemas = conduccionsistemas;
       this.riegosistemas = riegosistemas;
       this.variedades = variedades;
       this.cantidadPlantas = cantidadPlantas;
       this.tamanioHectariaVariedad = tamanioHectariaVariedad;
       this.anio = anio;
       this.detallevariedadcuarteleses = detallevariedadcuarteleses;
    }
   
    public Integer getIdDetalleVariedad() {
        return this.idDetalleVariedad;
    }
    
    public void setIdDetalleVariedad(Integer idDetalleVariedad) {
        this.idDetalleVariedad = idDetalleVariedad;
    }
    public Conduccionsistemas getConduccionsistemas() {
        return this.conduccionsistemas;
    }
    
    public void setConduccionsistemas(Conduccionsistemas conduccionsistemas) {
        this.conduccionsistemas = conduccionsistemas;
    }
    public Riegosistemas getRiegosistemas() {
        return this.riegosistemas;
    }
    
    public void setRiegosistemas(Riegosistemas riegosistemas) {
        this.riegosistemas = riegosistemas;
    }
    public Variedades getVariedades() {
        return this.variedades;
    }
    
    public void setVariedades(Variedades variedades) {
        this.variedades = variedades;
    }
    public Integer getCantidadPlantas() {
        return this.cantidadPlantas;
    }
    
    public void setCantidadPlantas(Integer cantidadPlantas) {
        this.cantidadPlantas = cantidadPlantas;
    }
    public Float getTamanioHectariaVariedad() {
        return this.tamanioHectariaVariedad;
    }
    
    public void setTamanioHectariaVariedad(Float tamanioHectariaVariedad) {
        this.tamanioHectariaVariedad = tamanioHectariaVariedad;
    }
    public Integer getAnio() {
        return this.anio;
    }
    
    public void setAnio(Integer anio) {
        this.anio = anio;
    }
    public Set getDetallevariedadcuarteleses() {
        return this.detallevariedadcuarteleses;
    }
    
    public void setDetallevariedadcuarteleses(Set detallevariedadcuarteleses) {
        this.detallevariedadcuarteleses = detallevariedadcuarteleses;
    }




}


