package com.pojos.model;
// Generated May 28, 2015 4:10:50 PM by Hibernate Tools 3.6.0



/**
 * Detallevariedadcuarteles generated by hbm2java
 */
public class Detallevariedadcuarteles  implements java.io.Serializable {


     private DetallevariedadcuartelesId id;
     private Direcciones direcciones;
     private Detallevariedades detallevariedades;
     private String cuartel;

    public Detallevariedadcuarteles() {
    }

	
    public Detallevariedadcuarteles(DetallevariedadcuartelesId id, Direcciones direcciones, Detallevariedades detallevariedades) {
        this.id = id;
        this.direcciones = direcciones;
        this.detallevariedades = detallevariedades;
    }
    public Detallevariedadcuarteles(DetallevariedadcuartelesId id, Direcciones direcciones, Detallevariedades detallevariedades, String cuartel) {
       this.id = id;
       this.direcciones = direcciones;
       this.detallevariedades = detallevariedades;
       this.cuartel = cuartel;
    }
   
    public DetallevariedadcuartelesId getId() {
        return this.id;
    }
    
    public void setId(DetallevariedadcuartelesId id) {
        this.id = id;
    }
    public Direcciones getDirecciones() {
        return this.direcciones;
    }
    
    public void setDirecciones(Direcciones direcciones) {
        this.direcciones = direcciones;
    }
    public Detallevariedades getDetallevariedades() {
        return this.detallevariedades;
    }
    
    public void setDetallevariedades(Detallevariedades detallevariedades) {
        this.detallevariedades = detallevariedades;
    }
    public String getCuartel() {
        return this.cuartel;
    }
    
    public void setCuartel(String cuartel) {
        this.cuartel = cuartel;
    }




}


