package com.pojos.model;
// Generated May 28, 2015 4:10:50 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Direcciones generated by hbm2java
 */
public class Direcciones  implements java.io.Serializable {


     private Integer idDireccion;
     private Detallesubregion detallesubregion;
     private String dirRol;
     private Integer dirTelefono1;
     private Integer dirTelefono2;
     private String dirNombre;
     private Float dirTamanoHectariaTotal;
     private Set detallevariedadcuarteleses = new HashSet(0);
     private Set entidadrazondireccioneses = new HashSet(0);

    public Direcciones() {
    }

    public Direcciones(Detallesubregion detallesubregion, String dirRol, Integer dirTelefono1, Integer dirTelefono2, String dirNombre, Float dirTamanoHectariaTotal, Set detallevariedadcuarteleses, Set entidadrazondireccioneses) {
       this.detallesubregion = detallesubregion;
       this.dirRol = dirRol;
       this.dirTelefono1 = dirTelefono1;
       this.dirTelefono2 = dirTelefono2;
       this.dirNombre = dirNombre;
       this.dirTamanoHectariaTotal = dirTamanoHectariaTotal;
       this.detallevariedadcuarteleses = detallevariedadcuarteleses;
       this.entidadrazondireccioneses = entidadrazondireccioneses;
    }
   
    public Integer getIdDireccion() {
        return this.idDireccion;
    }
    
    public void setIdDireccion(Integer idDireccion) {
        this.idDireccion = idDireccion;
    }
    public Detallesubregion getDetallesubregion() {
        return this.detallesubregion;
    }
    
    public void setDetallesubregion(Detallesubregion detallesubregion) {
        this.detallesubregion = detallesubregion;
    }
    public String getDirRol() {
        return this.dirRol;
    }
    
    public void setDirRol(String dirRol) {
        this.dirRol = dirRol;
    }
    public Integer getDirTelefono1() {
        return this.dirTelefono1;
    }
    
    public void setDirTelefono1(Integer dirTelefono1) {
        this.dirTelefono1 = dirTelefono1;
    }
    public Integer getDirTelefono2() {
        return this.dirTelefono2;
    }
    
    public void setDirTelefono2(Integer dirTelefono2) {
        this.dirTelefono2 = dirTelefono2;
    }
    public String getDirNombre() {
        return this.dirNombre;
    }
    
    public void setDirNombre(String dirNombre) {
        this.dirNombre = dirNombre;
    }
    public Float getDirTamanoHectariaTotal() {
        return this.dirTamanoHectariaTotal;
    }
    
    public void setDirTamanoHectariaTotal(Float dirTamanoHectariaTotal) {
        this.dirTamanoHectariaTotal = dirTamanoHectariaTotal;
    }
    public Set getDetallevariedadcuarteleses() {
        return this.detallevariedadcuarteleses;
    }
    
    public void setDetallevariedadcuarteleses(Set detallevariedadcuarteleses) {
        this.detallevariedadcuarteleses = detallevariedadcuarteleses;
    }
    public Set getEntidadrazondireccioneses() {
        return this.entidadrazondireccioneses;
    }
    
    public void setEntidadrazondireccioneses(Set entidadrazondireccioneses) {
        this.entidadrazondireccioneses = entidadrazondireccioneses;
    }




}


