package com.pojos.model;
// Generated May 28, 2015 4:10:50 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Entidades generated by hbm2java
 */
public class Entidades  implements java.io.Serializable {


     private String idEntidad;
     private String entRut;
     private Set bancoentidadeses = new HashSet(0);
     private Set entidadrazondireccioneses = new HashSet(0);
     private Set personaentidadeses = new HashSet(0);

    public Entidades() {
    }

	
    public Entidades(String idEntidad) {
        this.idEntidad = idEntidad;
    }
    public Entidades(String idEntidad, String entRut, Set bancoentidadeses, Set entidadrazondireccioneses, Set personaentidadeses) {
       this.idEntidad = idEntidad;
       this.entRut = entRut;
       this.bancoentidadeses = bancoentidadeses;
       this.entidadrazondireccioneses = entidadrazondireccioneses;
       this.personaentidadeses = personaentidadeses;
    }
   
    public String getIdEntidad() {
        return this.idEntidad;
    }
    
    public void setIdEntidad(String idEntidad) {
        this.idEntidad = idEntidad;
    }
    public String getEntRut() {
        return this.entRut;
    }
    
    public void setEntRut(String entRut) {
        this.entRut = entRut;
    }
    public Set getBancoentidadeses() {
        return this.bancoentidadeses;
    }
    
    public void setBancoentidadeses(Set bancoentidadeses) {
        this.bancoentidadeses = bancoentidadeses;
    }
    public Set getEntidadrazondireccioneses() {
        return this.entidadrazondireccioneses;
    }
    
    public void setEntidadrazondireccioneses(Set entidadrazondireccioneses) {
        this.entidadrazondireccioneses = entidadrazondireccioneses;
    }
    public Set getPersonaentidadeses() {
        return this.personaentidadeses;
    }
    
    public void setPersonaentidadeses(Set personaentidadeses) {
        this.personaentidadeses = personaentidadeses;
    }




}


