package com.pojos.model;
// Generated May 28, 2015 4:10:50 PM by Hibernate Tools 3.6.0



/**
 * EntidadrazondireccionesId generated by hbm2java
 */
public class EntidadrazondireccionesId  implements java.io.Serializable {


     private int idRazonSocial;
     private String idEntidad;
     private int idDireccion;
     private int idGiro;

    public EntidadrazondireccionesId() {
    }

    public EntidadrazondireccionesId(int idRazonSocial, String idEntidad, int idDireccion, int idGiro) {
       this.idRazonSocial = idRazonSocial;
       this.idEntidad = idEntidad;
       this.idDireccion = idDireccion;
       this.idGiro = idGiro;
    }
   
    public int getIdRazonSocial() {
        return this.idRazonSocial;
    }
    
    public void setIdRazonSocial(int idRazonSocial) {
        this.idRazonSocial = idRazonSocial;
    }
    public String getIdEntidad() {
        return this.idEntidad;
    }
    
    public void setIdEntidad(String idEntidad) {
        this.idEntidad = idEntidad;
    }
    public int getIdDireccion() {
        return this.idDireccion;
    }
    
    public void setIdDireccion(int idDireccion) {
        this.idDireccion = idDireccion;
    }
    public int getIdGiro() {
        return this.idGiro;
    }
    
    public void setIdGiro(int idGiro) {
        this.idGiro = idGiro;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EntidadrazondireccionesId) ) return false;
		 EntidadrazondireccionesId castOther = ( EntidadrazondireccionesId ) other; 
         
		 return (this.getIdRazonSocial()==castOther.getIdRazonSocial())
 && ( (this.getIdEntidad()==castOther.getIdEntidad()) || ( this.getIdEntidad()!=null && castOther.getIdEntidad()!=null && this.getIdEntidad().equals(castOther.getIdEntidad()) ) )
 && (this.getIdDireccion()==castOther.getIdDireccion())
 && (this.getIdGiro()==castOther.getIdGiro());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdRazonSocial();
         result = 37 * result + ( getIdEntidad() == null ? 0 : this.getIdEntidad().hashCode() );
         result = 37 * result + this.getIdDireccion();
         result = 37 * result + this.getIdGiro();
         return result;
   }   


}


