package com.pojos.model;
// Generated May 28, 2015 4:10:50 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Giros generated by hbm2java
 */
public class Giros  implements java.io.Serializable {


     private int idGiro;
     private String giro;
     private Set entidadrazondireccioneses = new HashSet(0);

    public Giros() {
    }

	
    public Giros(int idGiro) {
        this.idGiro = idGiro;
    }
    public Giros(int idGiro, String giro, Set entidadrazondireccioneses) {
       this.idGiro = idGiro;
       this.giro = giro;
       this.entidadrazondireccioneses = entidadrazondireccioneses;
    }
   
    public int getIdGiro() {
        return this.idGiro;
    }
    
    public void setIdGiro(int idGiro) {
        this.idGiro = idGiro;
    }
    public String getGiro() {
        return this.giro;
    }
    
    public void setGiro(String giro) {
        this.giro = giro;
    }
    public Set getEntidadrazondireccioneses() {
        return this.entidadrazondireccioneses;
    }
    
    public void setEntidadrazondireccioneses(Set entidadrazondireccioneses) {
        this.entidadrazondireccioneses = entidadrazondireccioneses;
    }




}


