package com.pojos.model;
// Generated May 28, 2015 4:10:50 PM by Hibernate Tools 3.6.0



/**
 * PersonaentidadesId generated by hbm2java
 */
public class PersonaentidadesId  implements java.io.Serializable {


     private String idPersona;
     private String idEntidad;
     private int idTipoUsuario;

    public PersonaentidadesId() {
    }

    public PersonaentidadesId(String idPersona, String idEntidad, int idTipoUsuario) {
       this.idPersona = idPersona;
       this.idEntidad = idEntidad;
       this.idTipoUsuario = idTipoUsuario;
    }
   
    public String getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(String idPersona) {
        this.idPersona = idPersona;
    }
    public String getIdEntidad() {
        return this.idEntidad;
    }
    
    public void setIdEntidad(String idEntidad) {
        this.idEntidad = idEntidad;
    }
    public int getIdTipoUsuario() {
        return this.idTipoUsuario;
    }
    
    public void setIdTipoUsuario(int idTipoUsuario) {
        this.idTipoUsuario = idTipoUsuario;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PersonaentidadesId) ) return false;
		 PersonaentidadesId castOther = ( PersonaentidadesId ) other; 
         
		 return ( (this.getIdPersona()==castOther.getIdPersona()) || ( this.getIdPersona()!=null && castOther.getIdPersona()!=null && this.getIdPersona().equals(castOther.getIdPersona()) ) )
 && ( (this.getIdEntidad()==castOther.getIdEntidad()) || ( this.getIdEntidad()!=null && castOther.getIdEntidad()!=null && this.getIdEntidad().equals(castOther.getIdEntidad()) ) )
 && (this.getIdTipoUsuario()==castOther.getIdTipoUsuario());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdPersona() == null ? 0 : this.getIdPersona().hashCode() );
         result = 37 * result + ( getIdEntidad() == null ? 0 : this.getIdEntidad().hashCode() );
         result = 37 * result + this.getIdTipoUsuario();
         return result;
   }   


}


