package com.pojos.model;
// Generated May 28, 2015 4:10:50 PM by Hibernate Tools 3.6.0



/**
 * Personaentidades generated by hbm2java
 */
public class Personaentidades  implements java.io.Serializable {


     private PersonaentidadesId id;
     private Entidades entidades;
     private Personas personas;
     private Tipousuarios tipousuarios;

    public Personaentidades() {
    }

    public Personaentidades(PersonaentidadesId id, Entidades entidades, Personas personas, Tipousuarios tipousuarios) {
       this.id = id;
       this.entidades = entidades;
       this.personas = personas;
       this.tipousuarios = tipousuarios;
    }
   
    public PersonaentidadesId getId() {
        return this.id;
    }
    
    public void setId(PersonaentidadesId id) {
        this.id = id;
    }
    public Entidades getEntidades() {
        return this.entidades;
    }
    
    public void setEntidades(Entidades entidades) {
        this.entidades = entidades;
    }
    public Personas getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Personas personas) {
        this.personas = personas;
    }
    public Tipousuarios getTipousuarios() {
        return this.tipousuarios;
    }
    
    public void setTipousuarios(Tipousuarios tipousuarios) {
        this.tipousuarios = tipousuarios;
    }




}


