package com.pojos.model;
// Generated May 28, 2015 4:10:50 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Personas generated by hbm2java
 */
public class Personas  implements java.io.Serializable {


     private String idPersona;
     private String perNombre;
     private String perUsuario;
     private String perPassword;
     private Set personaentidadeses = new HashSet(0);

    public Personas() {
    }

	
    public Personas(String idPersona, String perNombre) {
        this.idPersona = idPersona;
        this.perNombre = perNombre;
    }
    public Personas(String idPersona, String perNombre, String perUsuario, String perPassword, Set personaentidadeses) {
       this.idPersona = idPersona;
       this.perNombre = perNombre;
       this.perUsuario = perUsuario;
       this.perPassword = perPassword;
       this.personaentidadeses = personaentidadeses;
    }
   
    public String getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(String idPersona) {
        this.idPersona = idPersona;
    }
    public String getPerNombre() {
        return this.perNombre;
    }
    
    public void setPerNombre(String perNombre) {
        this.perNombre = perNombre;
    }
    public String getPerUsuario() {
        return this.perUsuario;
    }
    
    public void setPerUsuario(String perUsuario) {
        this.perUsuario = perUsuario;
    }
    public String getPerPassword() {
        return this.perPassword;
    }
    
    public void setPerPassword(String perPassword) {
        this.perPassword = perPassword;
    }
    public Set getPersonaentidadeses() {
        return this.personaentidadeses;
    }
    
    public void setPersonaentidadeses(Set personaentidadeses) {
        this.personaentidadeses = personaentidadeses;
    }




}


