package com.pojos.model;
// Generated May 28, 2015 4:10:50 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Razonsociales generated by hbm2java
 */
public class Razonsociales  implements java.io.Serializable {


     private int idRazonSocial;
     private String razNombre;
     private Set entidadrazondireccioneses = new HashSet(0);

    public Razonsociales() {
    }

	
    public Razonsociales(int idRazonSocial) {
        this.idRazonSocial = idRazonSocial;
    }
    public Razonsociales(int idRazonSocial, String razNombre, Set entidadrazondireccioneses) {
       this.idRazonSocial = idRazonSocial;
       this.razNombre = razNombre;
       this.entidadrazondireccioneses = entidadrazondireccioneses;
    }
   
    public int getIdRazonSocial() {
        return this.idRazonSocial;
    }
    
    public void setIdRazonSocial(int idRazonSocial) {
        this.idRazonSocial = idRazonSocial;
    }
    public String getRazNombre() {
        return this.razNombre;
    }
    
    public void setRazNombre(String razNombre) {
        this.razNombre = razNombre;
    }
    public Set getEntidadrazondireccioneses() {
        return this.entidadrazondireccioneses;
    }
    
    public void setEntidadrazondireccioneses(Set entidadrazondireccioneses) {
        this.entidadrazondireccioneses = entidadrazondireccioneses;
    }




}


