package com.pojos.model;
// Generated May 28, 2015 4:10:50 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Riegosistemas generated by hbm2java
 */
public class Riegosistemas  implements java.io.Serializable {


     private Integer idRiegoSistema;
     private String riegoSistema;
     private Set detallevariedadeses = new HashSet(0);

    public Riegosistemas() {
    }

    public Riegosistemas(String riegoSistema, Set detallevariedadeses) {
       this.riegoSistema = riegoSistema;
       this.detallevariedadeses = detallevariedadeses;
    }
   
    public Integer getIdRiegoSistema() {
        return this.idRiegoSistema;
    }
    
    public void setIdRiegoSistema(Integer idRiegoSistema) {
        this.idRiegoSistema = idRiegoSistema;
    }
    public String getRiegoSistema() {
        return this.riegoSistema;
    }
    
    public void setRiegoSistema(String riegoSistema) {
        this.riegoSistema = riegoSistema;
    }
    public Set getDetallevariedadeses() {
        return this.detallevariedadeses;
    }
    
    public void setDetallevariedadeses(Set detallevariedadeses) {
        this.detallevariedadeses = detallevariedadeses;
    }




}


