package com.pojos.model;
// Generated May 28, 2015 4:10:50 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Subregiones generated by hbm2java
 */
public class Subregiones  implements java.io.Serializable {


     private Integer idSubRegion;
     private Regionvitivinicolas regionvitivinicolas;
     private String subNombre;
     private Set detallesubregions = new HashSet(0);

    public Subregiones() {
    }

    public Subregiones(Regionvitivinicolas regionvitivinicolas, String subNombre, Set detallesubregions) {
       this.regionvitivinicolas = regionvitivinicolas;
       this.subNombre = subNombre;
       this.detallesubregions = detallesubregions;
    }
   
    public Integer getIdSubRegion() {
        return this.idSubRegion;
    }
    
    public void setIdSubRegion(Integer idSubRegion) {
        this.idSubRegion = idSubRegion;
    }
    public Regionvitivinicolas getRegionvitivinicolas() {
        return this.regionvitivinicolas;
    }
    
    public void setRegionvitivinicolas(Regionvitivinicolas regionvitivinicolas) {
        this.regionvitivinicolas = regionvitivinicolas;
    }
    public String getSubNombre() {
        return this.subNombre;
    }
    
    public void setSubNombre(String subNombre) {
        this.subNombre = subNombre;
    }
    public Set getDetallesubregions() {
        return this.detallesubregions;
    }
    
    public void setDetallesubregions(Set detallesubregions) {
        this.detallesubregions = detallesubregions;
    }




}


