package com.pojos.model;
// Generated May 28, 2015 4:10:50 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Tipovariedad generated by hbm2java
 */
public class Tipovariedad  implements java.io.Serializable {


     private Integer idTipoVariedad;
     private String tipoVariedad;
     private Set variedadeses = new HashSet(0);

    public Tipovariedad() {
    }

    public Tipovariedad(String tipoVariedad, Set variedadeses) {
       this.tipoVariedad = tipoVariedad;
       this.variedadeses = variedadeses;
    }
   
    public Integer getIdTipoVariedad() {
        return this.idTipoVariedad;
    }
    
    public void setIdTipoVariedad(Integer idTipoVariedad) {
        this.idTipoVariedad = idTipoVariedad;
    }
    public String getTipoVariedad() {
        return this.tipoVariedad;
    }
    
    public void setTipoVariedad(String tipoVariedad) {
        this.tipoVariedad = tipoVariedad;
    }
    public Set getVariedadeses() {
        return this.variedadeses;
    }
    
    public void setVariedadeses(Set variedadeses) {
        this.variedadeses = variedadeses;
    }




}


