package com.pojos.model;
// Generated May 28, 2015 4:10:50 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Tipousuarios generated by hbm2java
 */
public class Tipousuarios  implements java.io.Serializable {


     private int idTipoUsuario;
     private String tipoUsuario;
     private Set personaentidadeses = new HashSet(0);

    public Tipousuarios() {
    }

	
    public Tipousuarios(int idTipoUsuario) {
        this.idTipoUsuario = idTipoUsuario;
    }
    public Tipousuarios(int idTipoUsuario, String tipoUsuario, Set personaentidadeses) {
       this.idTipoUsuario = idTipoUsuario;
       this.tipoUsuario = tipoUsuario;
       this.personaentidadeses = personaentidadeses;
    }
   
    public int getIdTipoUsuario() {
        return this.idTipoUsuario;
    }
    
    public void setIdTipoUsuario(int idTipoUsuario) {
        this.idTipoUsuario = idTipoUsuario;
    }
    public String getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(String tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public Set getPersonaentidadeses() {
        return this.personaentidadeses;
    }
    
    public void setPersonaentidadeses(Set personaentidadeses) {
        this.personaentidadeses = personaentidadeses;
    }




}


