package com.pojos.model;
// Generated May 28, 2015 4:10:50 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Variedades generated by hbm2java
 */
public class Variedades  implements java.io.Serializable {


     private int idVariedad;
     private Tipovariedad tipovariedad;
     private String variedad;
     private Set detallevariedadeses = new HashSet(0);

    public Variedades() {
    }

	
    public Variedades(int idVariedad) {
        this.idVariedad = idVariedad;
    }
    public Variedades(int idVariedad, Tipovariedad tipovariedad, String variedad, Set detallevariedadeses) {
       this.idVariedad = idVariedad;
       this.tipovariedad = tipovariedad;
       this.variedad = variedad;
       this.detallevariedadeses = detallevariedadeses;
    }
   
    public int getIdVariedad() {
        return this.idVariedad;
    }
    
    public void setIdVariedad(int idVariedad) {
        this.idVariedad = idVariedad;
    }
    public Tipovariedad getTipovariedad() {
        return this.tipovariedad;
    }
    
    public void setTipovariedad(Tipovariedad tipovariedad) {
        this.tipovariedad = tipovariedad;
    }
    public String getVariedad() {
        return this.variedad;
    }
    
    public void setVariedad(String variedad) {
        this.variedad = variedad;
    }
    public Set getDetallevariedadeses() {
        return this.detallevariedadeses;
    }
    
    public void setDetallevariedadeses(Set detallevariedadeses) {
        this.detallevariedadeses = detallevariedadeses;
    }




}


