package com.pojos.model;
// Generated May 28, 2015 4:10:50 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Zonas generated by hbm2java
 */
public class Zonas  implements java.io.Serializable {


     private int idZona;
     private String zona;
     private Set detallesubregions = new HashSet(0);

    public Zonas() {
    }

	
    public Zonas(int idZona) {
        this.idZona = idZona;
    }
    public Zonas(int idZona, String zona, Set detallesubregions) {
       this.idZona = idZona;
       this.zona = zona;
       this.detallesubregions = detallesubregions;
    }
   
    public int getIdZona() {
        return this.idZona;
    }
    
    public void setIdZona(int idZona) {
        this.idZona = idZona;
    }
    public String getZona() {
        return this.zona;
    }
    
    public void setZona(String zona) {
        this.zona = zona;
    }
    public Set getDetallesubregions() {
        return this.detallesubregions;
    }
    
    public void setDetallesubregions(Set detallesubregions) {
        this.detallesubregions = detallesubregions;
    }




}


